src/carts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import cart_home, cart_update
urlpatterns = [
    url(r'^$', cart_home, name= 'home'),
    url(r'^update/$', cart_update, name= 'update'),
  ]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from carts.views import cart_home
from .views import home_page, about_page, contact_page, login_page, logout_form, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),

    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_form, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'products/', include("products.urls", namespace='products')),
    url(r'carts/', include("carts.urls", namespace='carts')),
    url(r'search/', include("search.urls", namespace='search')),
    
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import SearchProductListView
urlpatterns = [
    url(r'^$', SearchProductListView.as_view(), name= 'query'),
 ]

src/search/models.py
from django.db import models

# Create your models here.

src/search/views.py
from django.shortcuts import render
from django.views.generic import ListView
# Create your views here.
from products.models import Product

class SearchProductListView(ListView):
  template_name = "search/view.html"

  # def get_context_data(self, *args, **kwargs):
  #   context = super(ProductListView, self).get_context_data(*args, **kwargs)
  #   print(context)
  #   return context

# This function is overriden function
# It is used for searching and filtering purpose based on the given parameter
  def get_queryset(self, *args, **kwargs):
    request = self.request
    # get query parameter
    query = request.GET.get('q')
    # check if user has selected sort by name radio button
    sort_by_name = request.GET.get('name-sort')

    # check if user has selected sort by pricce radio button
    sort_by_price = request.GET.get('price-sort')
    print(sort_by_name, sort_by_price)
    #  if query is set check whether the user has selected radio buttons or not or not
    if query is not None:
      products = Product.objects.filter(title__icontains=query)
      if sort_by_name is not None and sort_by_price is not None:
        products = products.order_by('title', 'price')
      elif sort_by_price is None:
        products = products.order_by('-price')
      elif sort_by_name is None:
        products = products.order_by('title')

      return products
   
    return Product.objects.all()

src/search/templates/search/snippets/search-form.html
<div class="row">
  <div class="col-12">
    <form action="{% url 'search:query' %} ">
      <div class="row">
        <div class="col">
          <input type="text" class="form-control" placeholder="name" name='q'>
        </div>
        <div class="col">
          <label for="name-sort">Sort By Name</label>
          <input type="checkbox" name="name-sort" id="name-sort">
        </div>

        <div class="col">
          <label for="name-price">Sort By Price</label>
          <input type="checkbox" name="price-sort" id="name-price">
        </div>

        <div class="col">
          <input type="submit" class="form-control btn btn-success" value="search">
        </div>
      </div>
    </form>
  </div>

</div>