src/carts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import cart_home, cart_update
urlpatterns = [
    url(r'^$', cart_home, name= 'home'),
    url(r'^update/$', cart_update, name= 'update'),
  ]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from carts.views import cart_home
from .views import home_page, about_page, contact_page, login_page, logout_form, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),

    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_form, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'products/', include("products.urls", namespace='products')),
    url(r'carts/', include("carts.urls", namespace='carts')),
    url(r'search/', include("search.urls", namespace='search')),
    
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/products/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import ProductListView, ProductDetailView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name= 'list'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name= 'detail'),
    ]

src/templates/base/css.html
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

src/templates/base/js.html
{% load static %}

<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> -->

<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url%}
{% url 'register' as register_url %}
{% url 'carts:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{brand_name }} {% else %}Alazar Ecommerce {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapsed" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
          <a class="nav-link" href="{{ product_list_url }}">Products</a>
        </li>

        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}"> Cart <span class="cart-item-count"> {{request.session.cart_items}} </span>   </a>
        </li>
        
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
          <a class="nav-link" href="{{ register_url }}">Register</a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>