src/carts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import cart_home, cart_update
urlpatterns = [
    url(r'^$', cart_home, name= 'home'),
    url(r'^update/$', cart_update, name= 'update'),
  ]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from carts.views import cart_home
from .views import home_page, about_page, contact_page, login_page, logout_form, register_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),

    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_form, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'products/', include("products.urls", namespace='products')),
    url(r'carts/', include("carts.urls", namespace='carts')),
    url(r'search/', include("search.urls", namespace='search')),
    
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

src/products/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import ProductListView, ProductDetailView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name= 'list'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name= 'detail'),
    ]

src/products/models.py
from django.db import models
import random,os
from django.urls import reverse

# Function used to give unique name for each uploaded image
# Got the original idea from https://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def uplaod_image_path(instance, filename):
  new_filename = random.randint(1,10000000)
  base_name = os.path.basename(filename)
  name, ext = os.path.splitext(base_name)
  final_filename = f'{new_filename}{ext}'
  return f'products/{final_filename}'

class ProductManager(models.Manager):
  def get_by_id(self, id):
    qs =  self.get_queryset().filter(id=id)
    if qs.count() ==1:
      return qs.first()
    return None

# Product Model
class Product(models.Model):
  title = models.CharField(max_length=120)
  description = models.TextField()
  price = models.DecimalField(decimal_places=2, max_digits=20, default= 20.00)
  image = models.ImageField(upload_to=uplaod_image_path)
  # Used as category
  slug = models.SlugField(default='uncategorized')
  timestamp = models.DateTimeField(auto_now_add=True)

  objects = ProductManager()

  def get_absolute_url(self):
    return reverse("products:detail", kwargs={"pk":self.pk})

  def __str__(self):
    return self.title

 

src/products/forms.py
from django import forms

class ProductForm(forms.ModelForm):
  pass

src/products/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Product
from django.http import Http404
from carts.views import get_cart
# Create your views here.

class ProductListView(ListView):
  queryset = Product.objects.all()
  template_name = "products/list.html"
  
  def get_context_data(self, *args, **kwargs):
    cart_obj = get_cart(self.request)

    context = super(ProductListView,self).get_context_data(*args, **kwargs)
    context['cart'] = cart_obj
    print(cart_obj)
    return context
# 
# This class is used to show the details of each product 
# It inherits the built-in DetailView classes
class ProductDetailView(DetailView):
  # Get all products
  queryset = Product.objects.all()
  template_name = "products/detail.html"

  def get_context_data(self, *args, **kwargs):
    cart_obj = get_cart(self.request)
    context = super(ProductDetailView,self).get_context_data(*args, **kwargs)
    # Pass the cart the products in to the context
    # so that it can be used if user is not authenticated during adding to cart
    context['cart'] = cart_obj
    return context

src/products/templates/products/snippets/add-to-cart.html
<form class ='form-add-product'action="{% url 'carts:update' %} " method="POST">
  {% csrf_token %}
      <input type="hidden" class="form-control" value="{{ product.id }}"  name='product_id'>
      <input type="submit" class="form-control btn btn-success btn-small" style="width: 15%;" value="add to cart">
  </div>

src/products/templates/products/snippets/card.html
{% load static %}
<div class="card" style="width: 18rem;">
  {% if product.image %}
    <img class="card-img-top" src="{{ product.image.url}}" alt="Card image cap">
  {% else %}
    <img class="card-img-top"  src="{% static 'img/twitch.jpg' %}" alt="Card image cap">
  {% endif %}
  <div class="card-body">
    <h3 class="card-title">{{ product.title }}</h3>
    <p>added {{product.timestamp|timesince}} ago</p>
    <p class="card-text">{{ product.description }}</p>
    ${{ product.price }} <a href="{{ product.get_absolute_url}}" class="btn btn-primary">Detail</a>
    <!-- {% include 'products/snippets/add-to-cart.html' with product=product cart=cart %} -->
    <!-- <a href="{% url 'products:detail' pk=product.pk  %}" class="btn btn-default">Add to Card</a> -->
  </div>
</div>